const buzz = [
  'Adwords',
  'app',
  'applikation',
  'avvisningsfrekvens',
  'branded content',
  'content manager',
  'content editor',
  'content marketing',
  'content provider',
  'feed',
  'flöde',
  'hashtag',
  'inbound marketing',
  'konvertering',
  'likes',
  'gillamarkeringar',
  'LinkedIn',
  'metataggar',
  'nyckelord',
  'outbound marketing',
  'Periscope',
  'Pinterest',
  'podda',
  'regramma',
  'retweeta',
  'SEM',
  'SEO',
  'SERP',
  'smarketing',
  'SMM',
  'Snapchat',
  'social selling',
  'storytelling',
  'unika besökare',
  'UX',
  'micro-moments',
  'omni-channel',
  'blockchain',
  'geofencing',
  'brand safety',
  'user-generated content',
  'smart content',
  'attribution',
  'SISP',
  'inkubator',
  'science park',
  'accelerator',
  'coworking space',
  'co-creation',
  'cirkulär ekonomi',
  'cirkulära affärsmodeller',
  'hackathon',
  'facilitera',
  'innovation',
  'innovatör',
  'innovationsprocess',
  'öppen innovation',
  'inbound innovation',
  'innovationsmiljö',
  'innovationsstödssystem',
  'innovationssystem',
  'innovationsekosystem',
  'innovationshöjd',
  'investering',
  'investeringsfrämjande',
  'innovationskontor',
  'kluster',
  'scale-up',
  'startup',
  'SME',
  'SMF',
  'soft landing',
  'talangattraktion',
  'testbädd',
  'tillväxtföretag',
  'triple helix',
  'multi helix',
  'artificiell intelligens',
  'AI',
  'GPT',
  'DALL·E',
  'athleisure',
  'augmented reality',
  'autonoma fordon',
  'B2B',
  'B2C',
  'metadata',
  'big data',
  'BOPIS',
  'bricks and clicks',
  'chatbots',
  'cirkulär handel',
  'click & collect',
  'conscious consumerism',
  'conversational commerce',
  'CX',
  'computer vison',
  'digitala assistenter',
  'disruptiv handel',
  'drop shipping',
  'endless aisles',
  'facial recognition',
  'friktionsfri handel',
  'fulfillment',
  'fygital handel',
  'gamification',
  'green retailing',
  'internet of things',
  'kassalösa butiker',
  'kuraterat',
  'last mile',
  'marknadsplatser',
  'maskininlärning',
  'mobile checkout',
  'micro fulfillment center',
  'omniexperience',
  'personalisering',
  'prime now',
  'pure players',
  'retailtainment',
  'RFID',
  'ROPO',
  'same day delivery',
  'see now buy now',
  'sensorteknik',
  'skill',
  'transparens',
  'visual search',
  'voice commerce',
  'relaterade artiklar',
  'kreativ',
  'ansvarsfull',
  'analytisk',
  'positiv',
  'motiverad',
  'bred erfarenhet',
  'omfattande erfarenhet',
  'organisatorisk',
  'effektiv',
  'track record',
  'vertikal',
  'disruptive',
  'white label',
  'lean startup',
  'pivot',
  'USP',
  'growth hacking',
  'bootstrapping',
  'MVP',
  'exekvera',
  'unicorn',
  // 2026
  'zero-click',
  'hyperpersonaliserad AI',
  'mikroinnehåll',
  'micro content',
  'human-centric',
  'autenticitet',
  'real-time insights',
  'synergier',
  'synergi',
  'paradigmskifte',
  'paradigm',
  'CTR',
  'CRO',
  'KPI',
  'NPS',
  'NKI',
  'PPC',
  'ROI',
  'clickbait',
  'CPC',
  'CLV',
  'CRM',
  'MA',
  'marketing automation',
  'leverabler',
  'leverabel',
  'freemium',
  'SaaS',
  'PaaS',
  'agent',
  'agentisk AI',
  'hyperlokal',
  'infografik',
  'long tail',
  'martech',
  'micro-influencer',
  'organisk räckvidd',
  'pain points',
  'pain point',
  'prospect',
  'prospects',
  'repurposing',
  'second-screen',
  'storyscaping',
  'thought leader',
  'thought leaders',
  'thought leadership',
  'ToFu',
  'MoFu',
  'BoFu',
  'UGC',
  'användargenererat innehåll',
  'white paper',
  'ticket to the game',
  'game changer',
  'gamechanging',
  'alignment',
  'linjera',
  'dubbelklicka på',
  'empowerment',
  'empowered',
  'ChatGPT',
  'Claude',
  'Claude Code',
  'Anthropic',
  'Gemini',
  'DeepSeek',
  'den nya standarden inom',
  'generativ AI',
  'short-form video',
  'immersive experiences',
  'immersiva upplevelser',
  'personaliserade upplevelser',
  'AR/VR',
  'AR',
  'VR',
  'Salesforce',
  'bespoke',
  'custom',
  'kustomisera',
  'superkraft',
  'optimera',
  'slop',
  'pivotera',
  'iterera',
  'reiterera',
  'ansvarsfull AI',
  'bias',
  'proximity bias',
  'digital nomad',
  'digital användarupplevelse',
  'digital medarbetarupplevelse',
  'digital user experience',
  'digital employee experience',
  'DCX',
  'DEX',
  'EX',
  'lågt hängande frukt',
  'best practice',
  'hype',
  'hajpad',
  'hajpat',
  'employer branding',
  'arbetsgivarvarumärke',
  'implementera',
  'retention',
  'konkurrensfördel',
  'bristvara',
  'feedback',
  'psykologisk trygghet',
  'ledarskapsutveckling',
  'pulsmätning',
  'strategisk',
  'i praktiken',
  'rent krasst',
  'ökad transparens',
  'säkerställ att',
  'säkerställa att',
  'strukturera',
  'identifiera',
  'effektivisera',
  'transparent',
  'mänsklig granskning',
  'AI-verktyg',
  'digitalt mogen',
  'utvecklingsmöjligheter',
  'exempel från verkligheten',
  'karriärresa',
  'ambassadör',
  'ambassadörer',
  'riktlinjer',
  '1-1',
  '1-1-samtal',
  'feedback-loop',
  'feedback-loopar',
  'process',
  'processer',
  'prestation',
  'prestationer',
  'skills',
  'skills-first',
  'kartlägga',
  'kartläggning',
  'matcha',
  'matchning',
  'intern rörlighet',
  'global räckvidd',
  'bygga relationer',
  'AGI',
  'AI first',
  'AIaaS',
  'AIOps',
  'DevOps',
  'DevSecOps',
  'FinOps',
  'RevOps',
  'API',
  'gateway',
  'automation',
  'autonoma agenter',
  'black box',
  'blockkedja',
  'blockkedjor',
  'BI',
  'CI/CD',
  'cloud native',
  'containerisering',
  'CDN',
  'DXP',
  'resiliens',
  'data lake',
  'digital motståndskraft',
  'digital transformation',
  'transformation',
  'transformativ',
  'digital tvilling',
  'DORA',
  'Edge AI',
  'edge',
  'everything as code',
  'fullstack',
  'guardrails',
  'human-in-the-loop',
  'hyperautomation',
  'infrastruktur-som-kod',
  'IoT',
  'livscykelhantering',
  'LLM',
  'low-code/no-code',
  'microservices',
  'mikrotjänster',
  'multimodal',
  'on-prem',
  'RAG',
  'serverless',
  'SSO',
  'token',
  'tokens',
  'tokenisering',
  'vektordatabas',
]


export default buzz

//console.log(buzz.sort().join('\n'))

