const buzz = [
	'Adwords',
	'app',
	'applikation',
	'avvisningsfrekvens',
	'branded content',
	'content manager',
	'content editor',
	'content marketing',
	'content provider',
	'cookie',
	'feed',
	'flöde',
	'hashtag',
	'hootSuite',
	'inbound marketing',
	'konvertering',
	'likes',
	'gillamarkeringar',
	'linkedIn',
	'metataggar',
	'nyckelord',
	'outbound marketing',
	'Periscope',
	'Pinterest',
	'podda',
	'regramma',
	'retweeta',
	'SEM',
	'SEO',
	'SERP',
	'smarketing',
	'SMM',
	'Snapchat',
	'social selling',
	'storytelling',
	'unika besökare',
	'UX',
	'micro-moments',
	'omni-channel',
	'blockchain',
	'geofencing',
	'brand safety',
	'user-generated content',
	'smart content',
	'attribution',
	'SISP',
	'inkubator',
	'science park',
	'accelerator',
	'coworking space',
	'co-creation',
	'cirkulär ekonomi',
	'cirkulära affärsmodeller',
	'forskningsinstitut',
	'hackathon',
	'facilitera',
	'innovation',
	'innovatör',
	'innovationsprocess',
	'öppen innovation',
	'inbound innovation',
	'innovationsmiljö',
	'innovationsstödssystem',
	'innovationssystem',
	'innovationsekosystem',
	'innovationshöjd',
	'investering',
	'investeringsfrämjande',
	'innovationskontor',
	'kluster',
	'scale-up',
	'startup',
	'SME',
	'SMF',
	'soft landing',
	'talangattraktion',
	'testbädd',
	'tillväxtföretag',
	'triple helix',
	'uppfinnare',
	'multi helix',
	'artificiell intelligens',
	'AI',
	'GPT-3',
	'DALL·E',
	'athleisure',
	'augmented reality',
	'autonoma fordon',
	'B2B',
	'B2C',
	'metadata',
	'big data',
	'blockchain',
	'BOPIS',
	'bricks and clicks',
	'chatbots',
	'cirkulär handel',
	'click & collect',
	'conscious consumerism',
	'conversational commerce',
	'CX',
	'computer vison',
	'digitala assistenter',
	'disruptiv handel',
	'drop shipping',
	'endless aisles',
	'facial recognition',
	'friktionsfri handel',
	'fulfillment',
	'fygital handel',
	'gamification',
	'green retailing',
	'internet of things',
	'kassalösa butiker',
	'kuraterat',
	'last mile',
	'marknadsplatser',
	'maskininlärning',
	'mobile checkout',
	'micro fulfillment center',
	'new retail',
	'omniexperience',
	'personalisering',
	'prime now',
	'pure players',
	'retailtainment',
	'RFID',
	'robot retail',
	'ROPO',
	'same day delivery',
	'see now buy now',
	'sensorteknik',
	'skills',
	'transparens',
	'visual search',
	'voice commerce',
	'relaterade artiklar',
	'kreativ',
	'ansvarsfull',
	'analytisk',
	'positiv',
	'motiverad',
	'bred erfarenhet',
	'omfattande erfarenhet',
	'organisatorisk',
	'effektiv',
	'track record',
	'vertikal',
	'disruptive',
	'white label',
	'lean startup',
	'pivot',
	'USP',
	'growth hacking',
	'bootstrapping',
	'MVP',
	'exekvera',
	'unicorn',
]

export default buzz
